# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:9.6
    restart: always
    container_name: pg_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    networks:
     - nestjs

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080   
    networks:
     - nestjs
  #app:
    #build: 
    #  context: .
    #  dockerfile: Dockerfile
    #deploy:
    # replicas: 5
    #ports:
    # - "3000:3000"   
   # volumes:
   #  - /logs/:/src/log
   # depends_on:
   #  - db
   # networks:
   #  - nestjs

  #lb:
  # image: nginx:alpine
  # ports:
  #  - "80:80"
  # volumes:
  #  - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  #  - "./nginx/logs/:/var/log/nginx"
  # networks:
  #  - nestjs
  # depends_on:
  #  - app
  #filebeat:
  # image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
  # volumes:
  #  - './filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'

volumes:
  db:

networks:
  nestjs:
   driver: bridge 
   