# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080   
  app:
   build: 
    dockerfile: Dockerfile
   container_name: nestjs_app
   ports:
    - "3000:3000"   
   volumes:
    - /logs/:/src/log
  #filebeat:
  # build:
  #  context: ./filebeat
  #  dockerfile: Dockerfile
  # container_name: filebeat
  # command: filebeat -e -strict.perms=false
  # volumes:
  #  - ./nestjs-log/logs:/src/log
volumes:
  db: